import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const arimo = Arimo({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${arimo.className}`}>
      <body className="antialiased text-black bg-white">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
